
[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrd"

[[constraint]]
  name = "github.com/decred/dcrwallet"
  version = "release-v1.3.0-rc1"

[[constraint]]
  name = "github.com/decred/slog"
  version = "1.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  version = "2.1.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/haisum/recaptcha"

[[constraint]]
  name = "github.com/jrick/logrotate"
  version = "1.0.0"

[[constraint]]
  name = "github.com/zenazn/goji"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[prune]
  go-tests = true
  unused-packages = true
